/*
 * Varuna Docs
 *
 * PI Project
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

import (
	"os"
)

type DocsUploadBody struct {
	// The doc to upload.
	Doc **os.File `json:"doc,omitempty"`
}
